### ISSUE TITLE
I cant enable mod

### ISSUE THREAD

**Issue by Peternator** [zuev93/oni_multiplayer#38]
I instaled mod step by step but when i start the game i cant see host/join. and i cant enable mod. is it bcs i have windows 11 ? :D
or maybe bcs they update the game 2 days ago?

**Comment by Provaic76** [comment]
I am having the same issue I put everything in the correct places and the mod shows up in oni but it says that there is "no compatible mod found" and I am not sure what to do now, please help.

**Comment by zuev93** [comment]
[Provaic76](https://github.com/Provaic76),

Could you provide a screenshot of your mod folder and player.log please?

That will help us to debug the issue, Thanks!

**Comment by Cyakat** [comment]
My friend said he had the same issue and he had downloaded the repository source files instead of the released zip file.

This should be the name of the file in ONI
![image](https://user-images.githubusercontent.com/36944093/235591987-6cb18126-d304-49b9-9418-197d50ff46cb.png)
This is what the mods folder should look like
![image](https://user-images.githubusercontent.com/36944093/235592059-2ab83d60-a9ee-4e16-9390-e52fb8ada1e6.png)
![image](https://user-images.githubusercontent.com/36944093/235592111-08f59f83-ac09-425e-ab2e-ff6e3882b8bf.png)

**Comment by zuev93** [comment]
All reports about not being to enable the mod seems to be related to wrong file placement. Please take a look on the screenshots above and make sure that it looks similar.
