### ISSUE TITLE
Huge world, dupe, skill tree and research tree desync

### ISSUE THREAD

**Issue by Demiyanit** [zuev93/oni_multiplayer#74]
And lots of errors.

**Comment by zuev93** [comment]
Hi,
Thanks for the report.

Please be aware that the mod still in the active development, so it's expected that some parts are out of syncs.

We have #70 and #71 to cover several aspects. Other desyncs also will be fixed by various improvements (e.g. huge milestone https://github.com/zuev93/oni_multiplayer/milestone/1 ).

So please bare with us and will make it happen :)
